window.APPENDIX_DATA = {
    RULES: [
        ["Outbreak steps", ["#learning", "#cases", "#tools", "#quiz"],
            "<strong>The 10-Step Method:</strong> Mastery of the CDC's investigation sequence is critical. <br><br>1. Prepare<br>2. Verify Diagnosis<br>3. Confirm Outbreak<br>4. Case Definition<br>5. Descriptive Epi<br>6. Hypothesize<br>7. Test Hypothesis (Analytic)<br>8. Refine/Add Studies<br>9. Control Measures<br>10. Communicate Findings."],

        ["Study designs", ["#learning", "#quiz"],
            "<strong>Design Selection:</strong> Knowing which study fits the situation.<br><ul><li><strong>Cohort:</strong> Best for rare exposures. Calculates Relative Risk.</li><li><strong>Case-Control:</strong> Best for rare diseases or food/outbreaks. Calculates Odds Ratio.</li><li><strong>Cross-Sectional:</strong> Snapshot in time (Prevalence).</li></ul>"],

        ["Measures (AR, RR, OR, RD)", ["#tools", "#quiz", "#notesheet"],
            "<strong>Quantitative Epidemiology:</strong><br><ul><li><strong>Attack Rate:</strong> The percentage of an at-risk group that becomes ill.</li><li><strong>Relative Risk (RR):</strong> Risk in exposed / Risk in unexposed.</li><li><strong>Odds Ratio (OR):</strong> Odds of exposure in cases / Odds of exposure in controls.</li></ul>"],

        ["Epi curves/spot maps", ["#tools", "#cases", "#quiz"],
            "<strong>Descriptive Epi (Time & Place):</strong><br><ul><li><strong>Point Source:</strong> Single sharp peak, one incubation period.</li><li><strong>Propagated:</strong> Multiple peaks, growing waves, person-to-person spread.</li><li><strong>Spot Map:</strong> Geographic clustering of cases.</li></ul>"],

        ["Bias/confounding/EM", ["#learning", "#quiz"],
            "<strong>Systematic Errors:</strong><br><ul><li><strong>Selection Bias:</strong> Groups differ in ways other than exposure.</li><li><strong>Information Bias:</strong> Measurement error (Recall, Interviewer).</li><li><strong>Confounding:</strong> A third variable distorts the true association.</li></ul>"],

        ["Screening (Se/Sp, PPV, NPV)", ["#tools", "#quiz"],
            "<strong>test Validity:</strong><br><ul><li><strong>Sensitivity:</strong> Ability to identify positives (TP / All Sick).</li><li><strong>Specificity:</strong> Ability to identify negatives (TN / All Healthy).</li><li><strong>PPV:</strong> Probability a +test is actually sick.</li></ul>"],

        ["Control & prevention", ["#cases", "#learning"],
            "<strong>Public Health Action:</strong><br><ul><li><strong>Primary:</strong> Prevent before it happens (Vaccine).</li><li><strong>Secondary:</strong> catch it early (Screening).</li><li><strong>Tertiary:</strong> Treat/Rehab to prevent worsening.</li></ul>"],

        ["Communication/reporting", ["#learning"],
            "<strong>The Final Step:</strong> Communicating to stakeholders, ensuring privacy (HIPAA), and documenting findings for future reference."]
    ],
    BIASES: [
        ["Selection – Nonresponse", "Participants differ from nonparticipants", "Track response, weight, simplify sampling frame"],
        ["Selection – Healthy worker", "Employed groups look healthier", "Compare to appropriate worker referent"],
        ["Selection – Berkson", "Hospital cases/controls distort exposure", "Prefer population controls"],
        ["Survivorship", "Long-term survivors overrepresented", "Use inception cohorts"],
        ["Loss to follow-up", "Differential attrition", "Retention protocols; sensitivity analysis"],
        ["Recall", "Cases remember exposures better", "Use records; blinding; neutral prompts"],
        ["Interviewer", "Probing differs by status", "Training; blinding; scripts"],
        ["Misclassification – Non-diff", "Equal error in groups → bias to null", "Improve measurement; validation subsample"],
        ["Misclassification – Diff", "Error differs by group", "Standardize ascertainment; blinding"],
        ["Confounding", "Third variable distorts association", "Randomize, restrict, match, adjust, stratify"],
        ["Effect modification", "True heterogeneity", "Report stratum-specific; no adjustment"],
        ["Instrumentation", "Tool drift over time", "Calibration schedule"],
        ["Maturation", "Natural change over time", "Controls; interrupted time series"],
        ["History", "External events alter outcomes", "Document and adjust; ITS"],
        ["Regression to mean", "Extremes move toward mean", "Multiple baselines; controls"],
        ["Hawthorne", "Behavior changes when observed", "Run-in period; unobtrusive measures"],
        ["Placebo", "Expectations alter response", "Placebo control, blinding"],
        ["Contamination", "Controls receive intervention", "Cluster design; separation"],
        ["Carryover", "Prior period affects next", "Washout; parallel design"],
        ["Observer expectancy", "Coder expectations skew coding", "Double blinding; dual coding"],
        ["Publication", "Positive results overrepresented", "Pre-registration; report nulls"],
        ["Ecological", "Group-level effects misapplied to individuals", "Analyze at individual level"],
        ["Aggregation", "Combining heterogeneous groups hides truth", "Stratify; random effects"],
        ["Collinearity", "Predictors correlated", "Dimension reduction; penalization"],
        ["Overfitting", "Model captures noise", "Holdout/regularization"],
        ["Multiple testing", "Inflated Type I error", "Adjust alpha; pre-specify"],
        ["P-hacking", "Data dredging", "Analysis plan; transparency"],
        ["Outcome switching", "Change outcomes post-hoc", "Pre-register; version control"],
        ["Data leakage", "Train on test info", "Strict splits; audit"],
        ["Simpson’s paradox", "Trend reverses after stratification", "Stratify; causal diagrams"]
    ],
    MNEMS: [
        ["PVC-CDHACC", "Prepare, Verify, Case-def, Describe, Hypothesize, Analyze, Refine, Control, Communicate"],
        ["SPEC", "Sensitivity, PPV; Error types; Cutoffs"],
        ["METRIC", "Mean, Error, Trend, Rate, Incidence, CI"],
        ["CURVES", "Choose bin, Understand shape, Reconstruct exposure, Verify window, Explain spread, Summarize"],
        ["SNOUT", "Sensitivity => SeNsitive rules OUT (High sensitivity is good for ruling out disease)"],
        ["SPIN", "Specificity => SPecific rules IN (High specificity is good for ruling in disease)"],
        ["DDA", "Data, Design, Analysis (Triad of Epidemiology)"],
        ["RET EH", "Reservoir, Escape, Transmission, Entry, Host (Chain of Infection)"],
        ["P²STQ", "Population, Parameter, Sample, Statistic, Question (Stats Basics)"],
        ["FAIR", "Feasible, Ambitious, Imaginable, Relevant (Research Question)"]
    ],
    RESOURCES: [
        { title: "CDC Current Outbreak List", url: "https://www.cdc.gov/outbreaks/index.html", desc: "Real-time data on active US outbreaks." },
        { title: "Science Olympiad Official Site", url: "https://www.soinc.org/disease-detectives-b", desc: "Rules, clarifications, and official handouts." },
        { title: "WHO Disease Outbreak News", url: "https://www.who.int/emergencies/disease-outbreak-news", desc: "Global alerts and situation reports." },
        { title: "MMWR (Morbidity and Mortality Weekly Report)", url: "https://www.cdc.gov/mmwr/index.html", desc: "The 'Voice of CDC' - primary source for case studies." },
        { title: "Epiville (Columbia University)", url: "http://epiville.ccnmtl.columbia.edu/", desc: "Interactive simulations and learning modules." }
    ],
    flashcards: [
        { front: "Incidence", back: "New cases over a period of time / Population at risk" },
        { front: "Prevalence", back: "Existing cases at a point in time / Total population" },
        { front: "Attack Rate", back: "Ill / (Ill + Well) x 100" },
        { front: "Relative Risk (RR)", back: "[a/(a+b)] / [c/(c+d)]" },
        { front: "Odds Ratio (OR)", back: "(a*d) / (b*c)" },
        { front: "Sensitivity", back: "True Positives / (True Positives + False Negatives)" },
        { front: "Specificity", back: "True Negatives / (True Negatives + False Positives)" },
        { front: "Type I Error", back: "False Positive (Rejecting a true null hypothesis)" },
        { front: "Type II Error", back: "False Negative (Failing to reject a false null hypothesis)" },
        { front: "Confounding", back: "Distortion of association by a third variable related to both exposure and outcome" },
        { front: "Herd Immunity", back: "Resistance of a group to invasion and spread of an infectious agent" },
        { front: "R0 (Basic Reproduction Number)", back: "Average number of secondary cases produced by one case in a completely susceptible population" },
        { front: "Fomite", back: "Inanimate object that can transmit disease (e.g., doorknob)" },
        { front: "Vector", back: "Living organism that transmits disease (e.g., mosquito)" },
        { front: "Zoonosis", back: "Disease transmissible from animals to humans" },
        { front: "Endemic", back: "Constant presence of disease in a population" },
        { front: "Epidemic", back: "Disease occurrence in excess of normal expectancy" },
        { front: "Pandemic", back: "Epidemic occurring over a wide area (crossing international boundaries)" },
        { front: "Incubation Period", back: "Time from exposure to onset of symptoms" },
        { front: "Latent Period", back: "Time from infection to infectiousness" },
        { front: "Hippocrates", back: "First to attempt to explain disease occurrence from a rational rather than supernatural viewpoint (400 BC)" },
        { front: "John Graunt", back: "Published landmark analysis of mortality data in 1662; early vital statistics" },
        { front: "James Lind", back: "Designed first controlled experiment (1747) showing limes prevent scurvy" },
        { front: "Edward Jenner", back: "Developed smallpox vaccine using cowpox (1796)" },
        { front: "John Snow", back: "Father of Epidemiology; investigated cholera in London (1854) using spot maps" },
        { front: "Louis Pasteur", back: "Germ theory; developed vaccines for anthrax and rabies" },
        { front: "Robert Koch", back: "Formalized postulates to identify organisms with infectious diseases" },
        { front: "Joseph Goldberger", back: "Identified pellagra as a nutritional deficiency (1920)" },
        { front: "Mantel & Haenszel", back: "Developed statistical procedure for stratified analysis of case-control studies" },
        { front: "Doll & Hill", back: "Conducted landmark studies linking smoking to lung cancer (1950s)" },
        { front: "Wheel Model", back: "Places the host at the centre with physical, biologic and social environments around it" },
        { front: "Web of Causation", back: "Interconnected network of factors with no single necessary agent" },
        { front: "Rothman’s Causal Pie", back: "Component causes combine to form a sufficient cause (pie) that produces disease" },
        { front: "Healthy Worker Effect", back: "Bias where working populations appear healthier than the general population" },
        { front: "Length‑Time Bias", back: "Screening detects slower‑growing diseases more easily, making prognosis appear better" },
        { front: "Logistic Regression", back: "Multivariate model estimating adjusted odds ratios for binary outcomes" },
        { front: "Mantel-Haenszel OR", back: "Weighted average of strata-specific odds ratios to adjust for confounding" },
        { front: "Survival Analysis", back: "Statistics dealing with time-to-event data (e.g., Kaplan-Meier curves)" },
        { front: "IHR (2005)", back: "International Health Regulations: Legally binding framework for global health security" },
        { front: "Prion", back: "Abnormal protein that triggers other proteins to fold abnormally (e.g., CJD, Kuru)" },
        { front: "Analytic Epidemiology", back: "Study of determinants (Why/How); tests hypotheses" },
        { front: "Descriptive Epidemiology", back: "Study of distribution (Who/Where/When); generates hypotheses" },
        { front: "Vehicle", back: "Non-living intermediary that conveys agent (e.g. food, water, blood)" },
        { front: "Active Surveillance", back: "Health department solicits reports from providers (More expensive, accurate)" },
        { front: "Passive Surveillance", back: "Health department waits for reports (Cheaper, underreporting)" },
        { front: "Sentinel Surveillance", back: "Monitoring key sites to estimate wider trends" },
        { front: "Syndromic Surveillance", back: "Using pre-diagnosis data (e.g. OTC sales) for early warning" },
        { front: "Case Fatality Rate (CFR)", back: "Percentage of cases that result in death (Deaths / Cases)" },
        { front: "Crude Mortality Rate", back: "Total deaths / Total population (Not adjusted)" },
        { front: "Cause-Specific Rate", back: "Deaths from cause X / Total population" },
        { front: "Proportionate Mortality", back: "Deaths from cause X / Total Deaths" },
        { front: "Neonatal Mortality", back: "Deaths in first 28 days of life / Live births" },
        { front: "Infant Mortality", back: "Deaths in first year of life / Live births" },
        { front: "Maternal Mortality", back: "Maternal deaths / Live births" },
        { front: "Hyperendemic", back: "Disease constantly present at high incidence" },
        { front: "Holoendemic", back: "Prevalent disease affecting most children early in life (e.g. Malaria)" },
        { front: "Sporadic", back: "Occurring irregularly and infrequently" },
        { front: "Virulence", back: "Ability to cause SEVERE disease (Case Fatality Rate)" },
        { front: "Infectivity", back: "Ability to enter, survive, and multiply in host" },
        { front: "Pathogenicity", back: "Ability to cause CLINICAL disease (Symptoms)" }
    ],
    glossary: [
        { term: "Agent", definition: "A factor (microorganism, chemical, etc.) whose presence or absence is essential for disease." },
        { term: "Bias", definition: "Systematic deviation of results or inferences from the truth." },
        { term: "Carrier", definition: "Person or animal that harbors a specific infectious agent without discernible clinical disease." },
        { term: "Case-Control Study", definition: "Observational study comparing those with disease (cases) to those without (controls)." },
        { term: "Cluster", definition: "An aggregation of cases over a particular period closely grouped in time and space, regardless of whether the number is more than the expected number." },
        { term: "Cohort Study", definition: "Observational study comparing those exposed to a factor to those unexposed." },
        { term: "Cross-Sectional Study", definition: "Study examining the relationship between diseases and other variables at one point in time." },
        { term: "Epidemic", definition: "The occurrence of more cases of disease than expected in a given area or among a specific group of people over a particular period of time." },
        { term: "Epidemic Curve", definition: "Histogram showing the course of a disease outbreak or epidemic." },
        { term: "Fomite", definition: "An inanimate object that can be the vehicle for transmission of an infectious agent (e.g., bedding, towels, surgical instruments)." },
        { term: "Host", definition: "Person or other living animal that affords subsistence or lodgment to an infectious agent." },
        { term: "Incidence", definition: "A measure of the frequency with which a new case of illness occurs in a population over a period of time." },
        { term: "Index Case", definition: "The first case to come to the attention of the investigator." },
        { term: "Isolation", definition: "Separation of infected persons to prevent transmission." },
        { term: "Morbidity", definition: "Any departure, subjective or objective, from a state of physiological or psychological well-being." },
        { term: "Mortality Rate", definition: "A measure of the frequency of occurrence of death in a defined population." },
        { term: "Outbreak", definition: "Synonymous with epidemic, usually used for a more localized area." },
        { term: "Pandemic", definition: "An epidemic occurring over a very wide area (several countries or continents) and usually affecting a large proportion of the population." },
        { term: "Pathogenicity", definition: "The ability of an agent to cause disease." },
        { term: "Prevalence", definition: "The proportion of cases (new and existing) in a population at a given time." },
        { term: "Quarantine", definition: "Restriction of activities of well persons who have been exposed to a case." },
        { term: "Reservoir", definition: "Habitat in which the agent normally lives, grows, and multiplies." },
        { term: "Risk", definition: "The probability that an individual will be affected by, or die from, an illness or injury within a stated time or age span." },
        { term: "Risk Factor", definition: "Aspect of personal behavior or lifestyle, environmental exposure, or inborn/inherited characteristic associated with health conditions." },
        { term: "Surveillance", definition: "Systematic collection, analysis, interpretation, and dissemination of health data." },
        { term: "Transmission", definition: "Any mode or mechanism by which an infectious agent is spread." },
        { term: "Vector", definition: "An animate intermediary in the indirect transmission of an agent that carries the agent from a reservoir to a susceptible host." },
        { term: "Virulence", definition: "The ability of an infectious agent to cause severe disease." },
        { term: "Zoonosis", definition: "An infectious disease that is transmissible under natural conditions from vertebrate animals to humans." },
        { term: "Wheel Model", definition: "A causation model that emphasises the host at the centre of concentric rings representing physical, biologic and social environments." },
        { term: "Web of Causation", definition: "A representation of disease causation as a network of interconnected factors without a single necessary agent." },
        { term: "Causal Pie", definition: "A model where multiple component causes form a sufficient cause (pie) that produces disease when complete." },
        { term: "Healthy Worker Effect", definition: "A bias arising because employed populations tend to be healthier than the general population, potentially underestimating risk." },
        { term: "Length‑Time Bias", definition: "A bias introduced by screening when slowly progressing diseases are more likely to be detected than aggressive ones." },
        { term: "Logistic Regression", definition: "A statistical model used to estimate adjusted odds ratios for a binary outcome while controlling for multiple variables." },
        { term: "YPLL", definition: "Years of Potential Life Lost: Measure of premature mortality." },
        { term: "SMR", definition: "Standardized Mortality Ratio: Observed deaths / Expected deaths." },
        { term: "Age-Adjustment", definition: "Process to remove the effect of age differences when comparing rates." },
        { term: "Prion Disease", definition: "Disease caused by misfolded proteins (e.g. Mad Cow)." },
        { term: "Recency Bias", definition: "Tendency to weigh recent events more heavily." },
        { term: "Anchoring Bias", definition: "Tendency to rely too heavily on the first piece of information." },
        { term: "Analytic Epidemiology", definition: "Testing hypotheses about relationships (Determinants)." },
        { term: "Descriptive Epidemiology", definition: "Characterizing amount/distribution of disease (Person/Place/Time)." },
        { term: "Vehicle", definition: "Non-living intermediary (e.g. Food, Water, Biologics)." },
        { term: "Active Surveillance", definition: "Health dept contacts providers to solicit reports." },
        { term: "Passive Surveillance", definition: "Health dept waits for reports from providers." },
        { term: "Sentinel Surveillance", definition: "Monitoring key sites to infer general population health." },
        { term: "Syndromic Surveillance", definition: "Using pre-diagnostic data (ER visits, sales) for early warning." },
        { term: "Case Fatality Rate", definition: "Proportion of cases that result in death (Severity)." },
        { term: "Crude Rate", definition: "Summary rate based on actual number of events in total population." },
        { term: "Adjusted Rate", definition: "Rate statistically modified to remove effect of a confounder (e.g. Age)." },
        { term: "Hyperendemic", definition: "Disease present at consistently high levels." },
        { term: "Holoendemic", definition: "Disease affecting most of the population early in life." },
        { term: "Infant Mortality Rate", definition: "Deaths under 1 year of age per 1,000 live births." },
        { term: "Maternal Mortality Ratio", definition: "Maternal deaths per 100,000 live births." },
        { term: "Neonatal Mortality Rate", definition: "Deaths under 28 days of age per 1,000 live births." },
        { term: "Infectivity", definition: "Capacity to enter, survive, and multiply in a host." }
    ],
    FORMULAS: [
        { name: "Attack Rate (AR)", calc: "(Ill / Total Exposed) × 100", use: "% of group that became ill", category: "Frequency" },
        { name: "Relative Risk (RR)", calc: "[a/(a+b)] / [c/(c+d)]", use: "Cohort studies", category: "Association" },
        { name: "Odds Ratio (OR)", calc: "(a × d) / (b × c)", use: "Case-control studies", category: "Association" },
        { name: "Attributable Risk (AR)", calc: "I(exposed) - I(unexposed)", use: "Excess risk from exposure", category: "Impact" },
        { name: "AR% (Attributable Risk %)", calc: "[(RR - 1) / RR] × 100", use: "% of disease due to exposure", category: "Impact" },
        { name: "Vaccine Efficacy (VE)", calc: "[(AR(unvax) - AR(vax)) / AR(unvax)] × 100", use: "% reduction in disease", category: "Impact" },
        { name: "Sensitivity", calc: "a / (a + c)", use: "True positives / All sick", category: "Screening" },
        { name: "Specificity", calc: "d / (b + d)", use: "True negatives / All healthy", category: "Screening" },
        { name: "PPV (Positive Predictive Value)", calc: "a / (a + b)", use: "Probability positive test = sick", category: "Screening" },
        { name: "NPV (Negative Predictive Value)", calc: "d / (c + d)", use: "Probability negative test = healthy", category: "Screening" },
        { name: "Chi-Square", calc: "Σ [(O - E)² / E]", use: "Testing statistical significance", category: "Statistics" },
        { name: "Standard Error (RR)", calc: "√[(1/a) + (1/c) - (1/(a+b)) - (1/(c+d))]", use: "Confidence Intervals for RR", category: "Statistics" }
    ],
    TABLES: {
        chiSqure: {
            title: "Chi-Square Critical Values",
            headers: ["df", "p=0.10", "p=0.05", "p=0.01", "p=0.001"],
            rows: [
                [1, "2.706", "3.841", "6.635", "10.828"],
                [2, "4.605", "5.991", "9.210", "13.816"],
                [3, "6.251", "7.815", "11.345", "16.266"],
                [4, "7.779", "9.488", "13.277", "18.467"],
                [5, "9.236", "11.070", "15.086", "20.515"]
            ]
        },
        zTable: {
            title: "Common Z-Scores (Confidence Levels)",
            headers: ["Confidence Level", "Alpha (α)", "Z-Score (2-sided)"],
            rows: [
                ["90%", "0.10", "1.645"],
                ["95%", "0.05", "1.960"],
                ["99%", "0.01", "2.576"]
            ]
        }
    },
    DIAGNOSTIC: {
        metrics: [
            { name: "Sensitivity (TPR)", calc: "TP / (TP + FN)", desc: "Proportion of diseased people who test positive." },
            { name: "Specificity (TNR)", calc: "TN / (TN + FP)", desc: "Proportion of healthy people who test negative." },
            { name: "PPV", calc: "TP / (TP + FP)", desc: "Among positives, proportion who truly have disease." },
            { name: "NPV", calc: "TN / (TN + FN)", desc: "Among negatives, proportion who truly do not have disease." },
            { name: "Accuracy", calc: "(TP + TN) / Total", desc: "Overall correct classification rate." }
        ],
        checklist: [
            { category: "Foundation", items: ["Triad (Agent/Host/Env)", "Endemic vs Epidemic", "Surveillance Types"] },
            { category: "Math", items: ["2x2 Table Completion", "Sensitivity/Specificity Calc", "Epi Curve Interpretation"] }
        ]
    }
};

// console.log('[APPENDIX DATA] Loaded successfully');
// console.log('[APPENDIX DATA] Flashcards count:', window.APPENDIX_DATA.flashcards ? window.APPENDIX_DATA.flashcards.length : 0);
// console.log('[APPENDIX DATA] Glossary count:', window.APPENDIX_DATA.glossary ? window.APPENDIX_DATA.glossary.length : 0);
